Cluster:
  search_extent: 10 #pc
  distance_tolerance: 0.2 #20% for distance tolerance of stars in the region
  pmemb: 0.5
  plxquality: 10
psr_radial_tolerance: 1.4
# runaways3d
# runaways_path: "/home/surodeep/suro_aiu/traceback/cluster_runaway3d/"
# runaways2d
runaways_path: "/home/surodeep/suro_aiu/traceback/cluster_runaway/"

added_members:
  Alessi_Teutsch_5: []
  Berkeley_97: [2008383302396655488]
  Basel_8: [3326048448124872320, 3326023842254469120]
  RSG_8: [2013579250758906240]

observed_stars:
  Alessi_Teutsch_5: []
  Berkeley_97: [2008383302396655488, 2008430237808841600]
  RSG_8: [2013579250758906240, 2014377526259898240, 2013495997114201472]
  Basel_8: [3326048448124872320, 3326023842254469120, 3326026144355977472]


find_cluster:
  sigma_clip: 1.4

runaway_temp: 10000 #K


#CMD 3.7 settings

Evolutionary_tracks:
  PARSECv2.0: "/html/body/form/div/fieldset[1]/table/tbody/tr[3]/td[1]/input[1]"
  PARSECv1.2: "/html/body/form/div/fieldset[1]/table/tbody/tr[4]/td/input"

  COLOBRI_S_37: "/html/body/form/div/fieldset[1]/table/tbody/tr[5]/td/input"
  noCOLIBRI: "/html/body/form/div/fieldset[1]/table/tbody/tr[9]/td/input"

Photometric_system:
  YBC_new_Vega: "/html/body/form/div/fieldset[2]/table/tbody/tr[5]/td[1]/input"
  OBC: "/html/body/form/div/fieldset[2]/table/tbody/tr[6]/td[1]/input"

